name: integration-test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install node.js dependencies
        run: |
          cd Assignment02
          npm install

      - name: Install mysql
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
          sudo apt-get install mysql-client
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: creating database
        run: |
          echo ${{ secrets.DB_USERNAME }}
          mysql -h ${{ secrets.DB_HOST }} --port ${{ secrets.PORT }} -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
          mysql -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "USE ${{ secrets.DB_NAME }};" || exit 1

      - name: Run integration tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PORT: ${{ secrets.PORT }}
        run: |
          cd Assignment02
          npm run test

      - name: deleting redundant data
        run: |
          mysql -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "DROP DATABASE ${{ secrets.DB_NAME }};"
