name: packerbuild

on:
  pull_request:
    types: [closed]
    branches:
          - main

jobs:
  packer-check:
    name: Packer Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application artifact
        run: |
          zip -r webapp.zip .
          echo $(pwd)

      - name: create .env
        run: |
          touch /home/.env
          echo "PORT=3000" >> /home/.env
          echo "DB_NAME=csye6225" >> /home/.env
          echo "DB_USERNAME=root" >> /home/.env
          echo "DB_PASSWORD=Hello@123" >> /home/.env
          echo "DB_HOST=localhost" >> /home/.env
          echo $(pwd)

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: packer init
        run: |
          cd Assignment02
          packer init packer
    
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: packer build
        run: |
          cd Assignment02
          packer build packer