name: packervalidation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch :

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build application artifact
        run: |
          zip -r webapp.zip ../webapp

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: packer init
        run: |
          packer init Assignment02/packer
  
      - name: packer validate
        run: |
          packer validate Assignment02/packer


