name: packerbuild

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  packer-check:
    name: Packer Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application artifact
        run: |
          zip -r webapp.zip .
          echo $(pwd)

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: packer init
        run: |
          cd Assignment02
          packer init packer

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_KEY2 }}

      # Create a new Instance Template version
      - name: Create Instance Template version
        run: |
          gcloud compute instance-templates create csye-instance-template \
            --project="csye6225-414121" \
            --image="my-final-custom-image" \
            --machine-type=n1-standard-1 \
            --boot-disk-size=100 \
            --boot-disk-type=pd-balanced \
            --boot-disk-kms-key=projects/csye6225-414121/locations/global/keyRings/vm_key_3/cryptoKeys/vm_key_3 \
            --network="csye-vpc" \
            --subnet=webapp_subnet \
            --network-tier=PREMIUM \
            --tags=webapp \
            --metadata=startup-script="#!/bin/bash
            sudo bash -c 'cat <<EOF > /opt/unzippedWebapp/Assignment02/.env
            DB_USERNAME=webapp
            DB_NAME=webapp
            DB_PASSWORD=Hello@123
            DB_HOST=localhost
            PORT=3000
            EOF'
            sudo chown -R csye6225:csye6225 /opt/unzippedWebapp/Assignment02
            sudo chmod -R 755 /opt/unzippedWebapp/Assignment02
            sudo systemctl restart csye6225.service"

      # Update the managed instance group to use the new template
      - name: Update Managed Instance Group
        run: |
          gcloud compute instance-groups managed set-instance-template your-managed-instance-group \
            --template=csye-instance-template \
            --zone=your-zone

      # Start a rolling update for the managed instance group
      - name: Start Rolling Update
        run: |
          gcloud compute instance-groups managed rolling-action start-update your-managed-instance-group \
            --version=csye-instance-template \
            --zone=your-zone \
            --type=rolling-update

      # Wait for the managed instance group update to complete
      - name: Wait for Managed Instance Group Update
        run: |
          while [[ $(gcloud compute instance-groups managed describe your-managed-instance-group \
                    --zone=your-zone --format='value(versions.targetSize)' \
                    --filter='isStable = true') -lt 100 ]]; do
            echo "Waiting for managed instance group update to complete..."
            sleep 10
          done
