name: Continuous Integration for Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/
      
      - name: Packer init
        run: |
          packer init 

      - name: Packer fmt
        run: |
          if ! packer fmt -check .; then
            echo "Packer fmt detected formatting errors. Please fix them and try again."
            exit 1
          fi

      - name: Packer validate
        run: |
          if ! packer validate .; then
            echo "Packer template validation failed. Please fix the errors and try again."
            exit 1
          fi
