name: packervalidation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch :

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build application artifact
        run: |
          zip -r webapp.zip .
          echo $(pwd)

      - name: create .env
        run: |
          touch .env
          echo "PORT=3000" >> .env
          echo "DB_NAME=csye6225" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=Hello@123" >> .env
          echo "DB_HOST=localhost" >> .env
          echo $(pwd)

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: packer init
        run: |
          cd Assignment02
          packer init packer

      - name: packer fmt
        run: |
          cd Assignment02
          packer fmt -check packer
  
      - name: packer validate
        run: |
          cd Assignment02
          packer validate packer


